USE [master]
GO

/****** Object:  Database [BookDb]    Script Date: 2020-03-07 18:44:01 ******/
CREATE DATABASE [BookDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BookDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BookDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BookDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BookDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BookDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookDb] SET RECOVERY FULL 
GO

ALTER DATABASE [BookDb] SET  MULTI_USER 
GO

ALTER DATABASE [BookDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BookDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BookDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BookDb] SET  READ_WRITE 
GO

